import { getDocument } from '../documents/service.ts';
import type { RuntimeEnv } from '../env.ts';
import { defaultLocale, type SupportedLocale } from '../locales.ts';
import { renderPreviewDocument, renderPreviewTocItems } from '../starlight/preview-render.ts';

function previewShellPath(locale: SupportedLocale): string {
  return locale === defaultLocale ? '/cms-preview-shell/' : `/${locale}/cms-preview-shell/`;
}

function previewHeaders(asset: Response): Headers {
  const headers = new Headers(asset.headers);
  headers.delete('ETag');
  headers.delete('CF-Cache-Status');
  headers.delete('Content-Length');
  headers.set('Cache-Control', 'private, no-store');
  headers.set('X-Robots-Tag', 'noindex, nofollow');
  return headers;
}

function headingLevel(value: string | null, fallback: number): number {
  const level = Number(value);
  return Number.isInteger(level) && level >= 1 && level <= 6 ? level : fallback;
}

/**
 * Keep Preview on the protected admin path while reusing the actual Starlight
 * page frame and assets generated by the most recent public build.
 */
export async function previewDocument(env: RuntimeEnv, request: Request, id: string, locale: SupportedLocale): Promise<Response> {
  const document = await getDocument(env, id, locale);
  const shellRequest = new Request(new URL(previewShellPath(locale), request.url));
  const shell = await env.ASSETS.fetch(shellRequest);
  if (!shell.ok || !shell.headers.get('content-type')?.includes('text/html')) {
    throw new Error('Preview shell is unavailable. Rebuild the public site, then try again.');
  }

  const title = document.title || 'Untitled document';
  const preview = renderPreviewDocument(document.contentJson);
  let desktopLevels = { min: 2, max: 3 };
  let mobileLevels = { min: 2, max: 3 };
  const response = new HTMLRewriter()
    .on('title', { element: (element) => { element.setInnerContent(`${title} | Preview`); } })
    .on('meta[name="description"], meta[property="og:description"]', { element: (element) => { element.setAttribute('content', document.description); } })
    .on('meta[property="og:title"]', { element: (element) => { element.setAttribute('content', title); } })
    .on('meta[name="robots"]', { element: (element) => { element.setAttribute('content', 'noindex, nofollow'); } })
    .on('link[rel="canonical"]', { element: (element) => { element.remove(); } })
    // A preview is opened for one document locale. The public-site selector
    // would navigate to an empty static shell rather than this saved draft.
    .on('starlight-lang-select', { element: (element) => { element.remove(); } })
    .on('#_top', { element: (element) => { element.setInnerContent(title); } })
    .on('#cms-preview-content', { element: (element) => { element.setInnerContent(preview.html, { html: true }); } })
    .on('starlight-toc', { element: (element) => {
      desktopLevels = {
        min: headingLevel(element.getAttribute('data-min-h'), 2),
        max: headingLevel(element.getAttribute('data-max-h'), 3),
      };
    } })
    .on('mobile-starlight-toc', { element: (element) => {
      mobileLevels = {
        min: headingLevel(element.getAttribute('data-min-h'), 2),
        max: headingLevel(element.getAttribute('data-max-h'), 3),
      };
    } })
    .on('starlight-toc ul', { element: (element) => {
      element.setInnerContent(renderPreviewTocItems(preview.headings, desktopLevels.min, desktopLevels.max, element.getAttribute('class') ?? ''), { html: true });
    } })
    .on('mobile-starlight-toc ul', { element: (element) => {
      element.setInnerContent(renderPreviewTocItems(preview.headings, mobileLevels.min, mobileLevels.max, element.getAttribute('class') ?? ''), { html: true });
    } })
    .transform(shell);

  return new Response(response.body, { status: response.status, statusText: response.statusText, headers: previewHeaders(shell) });
}
